---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: default
type: Opaque
data:
  elastic-password: "cGFzc3dvcmQ=" # base64 от "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          env:
          
            - name: discovery.type
              value: "single-node"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: elastic-password
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
          ports:
            - containerPort: 9200
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: default
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: default
spec:
  rules:
    - host: minikube.local
      http:
        paths:
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-service
                port:
                  number: 9200